### PR TITLE
Add script to generate css minified for production and release

### PR DESCRIPTION
**Pull request by vromao**
## Comments
Adding npm script to generate minified css in project root (for release and easy use of another users):
- Compile scss with node-sass minifing output
- Run postcss-cli using autoprefixer replacing the original css input

With this solution we don't need to create caos in Webpack (to send minified css prod version to root and not to dist folder).

## Testing
To see **autoprefixer** working like a charm with a new class, put the following class in **src/shadow-sci.scss**:

```
.test {
  display: grid;
  transition: all .5s;
  user-select: none;
  background: linear-gradient(to bottom, white, black);
}
```

You'll see that some properties will have the prefixes in generate **./shadow-sci.min.css**

### CODE REVIEW

**Comment by gabrielaraujof** [comment]
What advantages would we have on placing the distribution files on root folder? And also, why would we use bare bundle configurations when we already have webpack as a dependency?

**Comment by vromao** [comment]
> What advantages would we have on placing the distribution files on root folder? And also, why would we use bare bundle configurations when we already have webpack as a dependency?

I think placing the distribution files in root makes easy access when someone is searching the file. Don't need to navigate between folders in github project to find it. I tried to make the output go to root with webpack but I can't achieve that. Because of that I make this config in scripts instead.

Heres an exemple of the popular balloon css lib when the files are on the root:
https://github.com/kazzkiq/balloon.css

**Comment by gabrielaraujof** [comment]
> I think placing the distribution files in root makes easy access when someone is searching the file. Don't need to navigate between folders in github project to find it.

I'm not a huge fan of this approach, since I'm used to libs that ship production-ready files inside a folder like `dist` or `css` (e.g. bootstrap, bulma, materializeCSS, semantic UI, etc). Also, I believe the most common way for using the lib nowadays would be through imports. The distribution version would be the exceptional case.

> I tried to make the output go to root with webpack but I can't achieve that. Because of that I make this config in scripts instead.

This can be easily done with [different configurations](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations) on webpack.

**Comment by vromao** [comment]
Thinking about a range of cases this solution ends up being limited, so it's closed. A Webpack solution will be open.

**Pull request closed without merging**
